title: Raul de SÃ¡ Durlo
theme: jekyll-theme-minimal
logo: /assets/img/bike.png
description: A simple portfolio whith my projects and code style.
toc: true
toc_sticky: true
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
